### ISSUE TITLE
generator.js broken

### ISSUE THREAD

**Issue by enoa7** [Snugug/generator-armadillo#9]
Hello!

I ran into some problems where I can't run 'grunt serve'

Loading "generator.js" tasks...ERROR
>> TypeError: undefined is not a function
Warning: Task "serve" not found. Use --force to continue.

Aborted due to warnings.

I tried re-installing my grunt-cli but its still broken. any thoughts?

/cheers

**Comment by Snugug** [comment]
The current version of Armadillo uses Gulp, not Grunt. Try just running `gulp`
